In [36]:
import requests
import pandas as pd
import json
import re
import time
from datetime import datetime
from bs4 import BeautifulSoup
from tqdm import tqdm
#Dinámico
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

#### Mexhome

In [37]:
#Datos de la búsqueda
cookies = {
    'utm_medium': 'Organic',
    '_pk_ref.2.513e': '%5B%2220615639987%22%2C%22%22%2C1772955324%2C%22%22%5D',
    '_pk_id.2.513e': 'cd01f928f7cfbb6c.1772955324.',
    '_pk_ses.2.513e': '1',
    '_gcl_gs': '2.1.k1$i1772955322$u57769398',
    '_gcl_au': '1.1.848721531.1772955325',
    '_gid': 'GA1.2.383899273.1772955325',
    '_gac_UA-77141872-1': '1.1772955325.CjwKCAiAqprNBhB6EiwAMe3yhpndmEpxCJcsLpOu0SiLnA0pN8xxt0DRUZX6GCb4OM1LeDAd1ibkzRoCgyEQAvD_BwE',
    '_dcid': 'dcid.1.1772955324427.447369708',
    '_cs_c': '0',
    '_tt_enable_cookie': '1',
    '_ttp': '01KK65YN6GJM8JEC2P31CR92MY_.tt.1',
    '_fbp': 'fb.1.1772955325729.733738153751410255',
    '_clck': '2c725y%5E2%5Eg46%5E0%5E2258',
    '__hstc': '111012570.9e69c4a258a6a77266b632b488e08757.1772955326448.1772955326448.1772955326448.1',
    'hubspotutk': '9e69c4a258a6a77266b632b488e08757',
    '__hssrc': '1',
    '_gcl_aw': 'GCL.1772955336.CjwKCAiAqprNBhB6EiwAMe3yhpndmEpxCJcsLpOu0SiLnA0pN8xxt0DRUZX6GCb4OM1LeDAd1ibkzRoCgyEQAvD_BwE',
    'AMP_MKTG_8f1ede8e9c': 'JTdCJTdE',
    '_ga': 'GA1.2.389813916.1772955325',
    '_cs_id': '851f46a4-4a05-a8ae-efb5-0f2668566894.1772955325.1.1772956158.1772955325.1.1807119325561.1.x',
    '_uetsid': '5f7de7f01ac111f1964cc31ec0652ef0',
    '_uetvid': '5f7e34801ac111f1a93f81a51bb7ddc4',
    'cf_clearance': 'OgnVviwZnLATWkpky165yXIjPUURKB4hWscDq0VPlqY-1772956158-1.2.1.1-erRrDQ5yGD.hBPaRSoiqkASp6IPpmyjRXL1aH9AlRJ_32Znj5b9dWdRXnP0sKfpQXuBFZGKgojw4ZPk4PftPN_IqtcXVnhncSubXC6ofOrVnGHNUMLtUqgCPIkc2Kqtsgj4yAQ.KAO0ESZHz5TWY3fVIv3sH1wUN6mc17GyyB4xQnivdYv.SABb.OUMmh5WnuifrSF1PmyCsj6a9LDjqaDJIvNNQvzd34KHAAinDaXw',
    'AMP_8f1ede8e9c': 'JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJjNTBkODBiZC0zMTllLTQ1MjYtYTM5Mi04MGM3ZWQwMzBhN2ElMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzcyOTU1MzI0NTY1JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlN0Q=',
    'AMP_8f1ede8e9c': 'JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJjNTBkODBiZC0zMTllLTQ1MjYtYTM5Mi04MGM3ZWQwMzBhN2ElMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzcyOTU1MzI0NTY1JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlN0Q=',
    '_ga_CTS53R3DBH': 'GS2.1.s1772955325$o1$g1$t1772956160$j58$l0$h0',
    '__hssc': '111012570.4.1772955326448',
    '__cf_bm': 'DBGCpslWzvqhP87JYbFamnHjrgLUcjXAjt82wpRLQ7Q-1772956284-1.0.1.1-DsnWFvuUHoOqwNQHLijnTCIy89jmYp2KlnezrRxyyyY92OFR0JRFbJpa5LjIE5_uSRfz7tZ6sGxqPrsjMk6VLu9up7fkgNkCz5cR8MtJrmo',
    '_clsk': '1jlmhhq%5E1772956561515%5E6%5E1%5Ez.clarity.ms%2Fcollect',
    'ttcsid': '1772955325650::SfllbTjREIyGkeZXme2o.1.1772956573866.0',
    'ttcsid_D0VRTLBC77UD7ROKAVV0': '1772955325650::fFtKR46ICBPMEhQ0J1Y4.1.1772956573866.1',
    '_cs_s': '6.0.U.9.1772958451081',
}

headers = {
    'accept': 'application/json, text/plain, */*',
    'accept-language': 'es-US,es-419;q=0.9,es;q=0.8',
    'authorization': 'Bearer mh_5eb147b78b1140d1b46681ad82fbe55a095f89b605f9270c645049bc2f62f7c1',
    'priority': 'u=1, i',
    'referer': 'https://mexhome.com/properties?area=puerto-escondido&type=',
    'sec-ch-ua': '"Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36',
    # 'cookie': 'utm_medium=Organic; _pk_ref.2.513e=%5B%2220615639987%22%2C%22%22%2C1772955324%2C%22%22%5D; _pk_id.2.513e=cd01f928f7cfbb6c.1772955324.; _pk_ses.2.513e=1; _gcl_gs=2.1.k1$i1772955322$u57769398; _gcl_au=1.1.848721531.1772955325; _gid=GA1.2.383899273.1772955325; _gac_UA-77141872-1=1.1772955325.CjwKCAiAqprNBhB6EiwAMe3yhpndmEpxCJcsLpOu0SiLnA0pN8xxt0DRUZX6GCb4OM1LeDAd1ibkzRoCgyEQAvD_BwE; _dcid=dcid.1.1772955324427.447369708; _cs_c=0; _tt_enable_cookie=1; _ttp=01KK65YN6GJM8JEC2P31CR92MY_.tt.1; _fbp=fb.1.1772955325729.733738153751410255; _clck=2c725y%5E2%5Eg46%5E0%5E2258; __hstc=111012570.9e69c4a258a6a77266b632b488e08757.1772955326448.1772955326448.1772955326448.1; hubspotutk=9e69c4a258a6a77266b632b488e08757; __hssrc=1; _gcl_aw=GCL.1772955336.CjwKCAiAqprNBhB6EiwAMe3yhpndmEpxCJcsLpOu0SiLnA0pN8xxt0DRUZX6GCb4OM1LeDAd1ibkzRoCgyEQAvD_BwE; AMP_MKTG_8f1ede8e9c=JTdCJTdE; _ga=GA1.2.389813916.1772955325; _cs_id=851f46a4-4a05-a8ae-efb5-0f2668566894.1772955325.1.1772956158.1772955325.1.1807119325561.1.x; _uetsid=5f7de7f01ac111f1964cc31ec0652ef0; _uetvid=5f7e34801ac111f1a93f81a51bb7ddc4; cf_clearance=OgnVviwZnLATWkpky165yXIjPUURKB4hWscDq0VPlqY-1772956158-1.2.1.1-erRrDQ5yGD.hBPaRSoiqkASp6IPpmyjRXL1aH9AlRJ_32Znj5b9dWdRXnP0sKfpQXuBFZGKgojw4ZPk4PftPN_IqtcXVnhncSubXC6ofOrVnGHNUMLtUqgCPIkc2Kqtsgj4yAQ.KAO0ESZHz5TWY3fVIv3sH1wUN6mc17GyyB4xQnivdYv.SABb.OUMmh5WnuifrSF1PmyCsj6a9LDjqaDJIvNNQvzd34KHAAinDaXw; AMP_8f1ede8e9c=JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJjNTBkODBiZC0zMTllLTQ1MjYtYTM5Mi04MGM3ZWQwMzBhN2ElMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzcyOTU1MzI0NTY1JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlN0Q=; AMP_8f1ede8e9c=JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJjNTBkODBiZC0zMTllLTQ1MjYtYTM5Mi04MGM3ZWQwMzBhN2ElMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzcyOTU1MzI0NTY1JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlN0Q=; _ga_CTS53R3DBH=GS2.1.s1772955325$o1$g1$t1772956160$j58$l0$h0; __hssc=111012570.4.1772955326448; __cf_bm=DBGCpslWzvqhP87JYbFamnHjrgLUcjXAjt82wpRLQ7Q-1772956284-1.0.1.1-DsnWFvuUHoOqwNQHLijnTCIy89jmYp2KlnezrRxyyyY92OFR0JRFbJpa5LjIE5_uSRfz7tZ6sGxqPrsjMk6VLu9up7fkgNkCz5cR8MtJrmo; _clsk=1jlmhhq%5E1772956561515%5E6%5E1%5Ez.clarity.ms%2Fcollect; ttcsid=1772955325650::SfllbTjREIyGkeZXme2o.1.1772956573866.0; ttcsid_D0VRTLBC77UD7ROKAVV0=1772955325650::fFtKR46ICBPMEhQ0J1Y4.1.1772956573866.1; _cs_s=6.0.U.9.1772958451081',
}

response = requests.get(
    'https://mexhome.com/wp-json/mh/v1/properties?expand=photos,location&per_page=42&area=puerto-escondido',
    cookies=cookies,
    headers=headers,
)

data=response.json()

print("Total de registros:", len(data))

Total de registros: 40

In [38]:
data

[{'id': 717771,
  'link': 'https://mexhome.com/property/vivo-building-f-632/',
  'link_es': 'https://mexhome.com/es/property/vivo-building-f-632/',
  'name': 'Vivo &#8211; Building F &#8211; 632',
  'details': {'property_mls_id': '',
   'property_list_price_usd': '295000',
   'property_bedrooms': '2',
   'property_baths': '2',
   'property_total_sqft': '',
   'property_lot_m2': '',
   'property_type': 'Condos',
   'property_community': '',
   'is_mexhome_listing': '0',
   'property_photos': [],
   'item_location': []}},
 {'id': 709385,
  'link': 'https://mexhome.com/property/vivo-building-h-833/',
  'link_es': 'https://mexhome.com/es/property/vivo-building-h-833/',
  'name': 'Vivo &#8211; Building H &#8211; 833',
  'details': {'property_mls_id': '',
   'property_list_price_usd': '685000',
   'property_bedrooms': '4',
   'property_baths': '3',
   'property_total_sqft': '',
   'property_lot_m2': '',
   'property_type': 'Condos',
   'property_thumbnail_image_url': '/wp-content/uploads/2025/09/IMG_37972028129-3-150x150.jpg',
   'property_community': '',
   'is_mexhome_listing': '0',
   'property_photos': [{'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Ro5/ea03fc3ux/IMG_3797%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Ro5/ca7phggcz/IMG_3784%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Ro5/2n8kqgugs/IMG_3786%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Ro5/7hdhh6039/IMG_3787%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Ro5/q9niiat8p/IMG_3789%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Ro5/2d6b5esv0/IMG_3790%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Ro5/pb0tz4kcb/IMG_3791%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Ro5/meh1exief/IMG_3792%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Ro5/nbkmvv9ip/IMG_3794%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Ro5/w124kdyg2/IMG_3795%20%281%29.jpg'}],
   'item_location': {'lat': '15.915630',
    'lng': '-97.185896',
    'zoom': 11,
    'state': 'Oaxaca'}}},
 {'id': 711608,
  'link': 'https://mexhome.com/property/vivo-villa-lots-28/',
  'link_es': 'https://mexhome.com/es/property/vivo-villa-lots-28/',
  'name': 'Vivo &#8211; Villa Lots &#8211; 28',
  'details': {'property_mls_id': '',
   'property_list_price_usd': '149000',
   'property_bedrooms': '',
   'property_baths': '',
   'property_total_sqft': '',
   'property_lot_m2': '',
   'property_type': 'Land',
   'property_thumbnail_image_url': '/wp-content/uploads/2025/10/Lot28-1-150x150.png',
   'property_community': 'Vivo - Villa Lots - Ocean B',
   'is_mexhome_listing': '0',
   'property_photos': [{'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002SYu/1dy3i7tf8/Lot28.png'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002SYu/bcasra4pp/Lot28zoom.png'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002SYu/mzvjjy5ll/VivoVillaHomesite_28.png'}],
   'item_location': {'lat': '15.915738', 'lng': '-97.182546', 'zoom': 11}}},
 {'id': 711712,
  'link': 'https://mexhome.com/property/325-vivo-building-c/',
  'link_es': 'https://mexhome.com/es/property/325-vivo-building-c/',
  'name': '325 Vivo &#8211; Building C',
  'details': {'property_mls_id': '',
   'property_list_price_usd': '128900',
   'property_bedrooms': '0',
   'property_baths': '1',
   'property_total_sqft': '',
   'property_lot_m2': '',
   'property_type': 'Condos',
   'property_community': '',
   'is_mexhome_listing': '0',
   'property_photos': [],
   'item_location': []}},
 {'id': 711969,
  'link': 'https://mexhome.com/property/vivo-building-e-531/',
  'link_es': 'https://mexhome.com/es/property/vivo-building-e-531/',
  'name': 'Vivo &#8211; Building E &#8211; 531',
  'details': {'property_mls_id': '',
   'property_list_price_usd': '425000',
   'property_bedrooms': '3',
   'property_baths': '2',
   'property_total_sqft': '',
   'property_lot_m2': '',
   'property_type': 'Condos',
   'property_thumbnail_image_url': '/wp-content/uploads/2025/10/IMG_4281-150x150.jpg',
   'property_community': '',
   'is_mexhome_listing': '0',
   'property_photos': [{'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rnd/unjso9vq5/IMG_4281.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rnd/qn2d6f793/IMG_4257.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rnd/xawwel6h7/IMG_4259.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rnd/8lng7tsrc/IMG_4261.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rnd/aeh7mlums/IMG_4265.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rnd/i24p1524b/IMG_4266.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rnd/zvwhdasri/IMG_4270.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rnd/wsadpf513/IMG_4271.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rnd/v707wvsey/IMG_4272.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rnd/1usx5tucx/IMG_4274.jpg'}],
   'item_location': {'lat': '15.915336',
    'lng': '-97.185159',
    'zoom': 11,
    'state': 'Oaxaca'}}},
 {'id': 712243,
  'link': 'https://mexhome.com/property/vivo-villa-home-41-casa-sol/',
  'link_es': 'https://mexhome.com/es/property/vivo-villa-home-41-casa-sol/',
  'name': 'Vivo &#8211; Villa Home &#8211; 41 (Casa Sol)',
  'details': {'property_mls_id': '',
   'property_list_price_usd': '699000',
   'property_bedrooms': '3',
   'property_baths': '3',
   'property_total_sqft': '',
   'property_lot_m2': '',
   'property_type': 'Houses',
   'property_community': 'Vivo - Villa Lots - Ocean A',
   'is_mexhome_listing': '0',
   'property_photos': [],
   'item_location': []}},
 {'id': 712672,
  'link': 'https://mexhome.com/property/barbarians-ocean-view-eco-retreat-center/',
  'link_es': 'https://mexhome.com/es/property/barbarians-ocean-view-eco-retreat-center/',
  'name': 'Barbarians Ocean View Eco Retreat Center',
  'details': {'property_mls_id': '',
   'property_list_price_usd': '2100000',
   'property_bedrooms': '',
   'property_baths': '',
   'property_total_sqft': '',
   'property_lot_m2': '',
   'property_type': '',
   'property_community': '',
   'is_mexhome_listing': '0',
   'property_photos': [],
   'item_location': {'lat': '15.83344', 'lng': '-97.04486', 'zoom': 11}}},
 {'id': 713663,
  'link': 'https://mexhome.com/property/vivo-building-marino-1343/',
  'link_es': 'https://mexhome.com/es/property/vivo-building-marino-1343/',
  'name': 'Vivo &#8211; Building Marino &#8211; 1343',
  'details': {'property_mls_id': '',
   'property_list_price_usd': '375000',
   'property_bedrooms': '2',
   'property_baths': '2',
   'property_total_sqft': '',
   'property_lot_m2': '',
   'property_type': 'Condos',
   'property_thumbnail_image_url': '/wp-content/uploads/2025/11/IMG_6059-150x150.jpg',
   'property_community': '',
   'is_mexhome_listing': '0',
   'property_photos': [{'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rok/i8xg7de1q/IMG_6059.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rok/slaxgw711/IMG_6060.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rok/lhqa8wklx/IMG_6061.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rok/8mw9vuvek/IMG_6062.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rok/swdtu997t/IMG_6063.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rok/ctv89bq2u/IMG_6065.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rok/a50cioia3/IMG_6066.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rok/on0f47q66/IMG_6067.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rok/u5g6vd3cf/IMG_6068.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rok/l1ogi8kv7/IMG_6069.jpg'}],
   'item_location': {'lat': '15.916033',
    'lng': '-97.186544',
    'zoom': 11,
    'state': 'Oaxaca'}}},
 {'id': 713666,
  'link': 'https://mexhome.com/property/vivo-villa-casa-paraiso/',
  'link_es': 'https://mexhome.com/es/property/vivo-villa-casa-paraiso/',
  'name': 'Vivo &#8211; Villa &#8211; Casa Paraiso',
  'details': {'property_mls_id': '',
   'property_list_price_usd': '575000',
   'property_bedrooms': '',
   'property_baths': '',
   'property_total_sqft': '',
   'property_lot_m2': '',
   'property_type': '',
   'property_community': '',
   'is_mexhome_listing': '0',
   'property_photos': [],
   'item_location': {'lat': '9.01815', 'lng': '-76.26268', 'zoom': 11}}},
 {'id': 714592,
  'link': 'https://mexhome.com/property/vivo-building-laguna-1224/',
  'link_es': 'https://mexhome.com/es/property/vivo-building-laguna-1224/',
  'name': 'Vivo &#8211; Building Laguna &#8211; 1224',
  'details': {'property_mls_id': '',
   'property_list_price_usd': '370000',
   'property_bedrooms': '2',
   'property_baths': '2',
   'property_total_sqft': '',
   'property_lot_m2': '',
   'property_type': 'Condos',
   'property_thumbnail_image_url': '/wp-content/uploads/2025/12/Copy20of20vivo_condo_1224_2019-11-22-0029IMG_8429-HDR2028129-150x150.jpg',
   'property_community': '',
   'is_mexhome_listing': '0',
   'property_photos': [{'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoI/16bk20tkg/Copy%20of%20vivo_condo_1224_2019-11-22-0029IMG_8429-HDR%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoI/i9yjn2qcm/Copy%20of%20vivo_condo_1224_2019-11-22-0001IMG_8325%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoI/sib967i9r/Copy%20of%20vivo_condo_1224_2019-11-22-0002IMG_8327%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoI/4vur4a5f2/Copy%20of%20vivo_condo_1224_2019-11-22-0006IMG_8334-HDR%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoI/05r22m9ik/Copy%20of%20vivo_condo_1224_2019-11-22-0008IMG_8340-HDR%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoI/gi4w61riq/Copy%20of%20vivo_condo_1224_2019-11-22-0012IMG_8351-HDR%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoI/5l27penuf/Copy%20of%20vivo_condo_1224_2019-11-22-0013IMG_8354-HDR%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoI/tgn4icx17/Copy%20of%20vivo_condo_1224_2019-11-22-0014IMG_8357-HDR%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoI/zk9ot6f79/Copy%20of%20vivo_condo_1224_2019-11-22-0015IMG_8360-HDR%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoI/m15r2wsr4/Copy%20of%20vivo_condo_1224_2019-11-22-0017IMG_8378-HDR%20%281%29.jpg'}],
   'item_location': {'lat': '15.915847', 'lng': '-97.186259', 'zoom': 11}}},
 {'id': 705565,
  'link': 'https://mexhome.com/property/vivo-building-marino-1311/',
  'link_es': 'https://mexhome.com/es/property/vivo-building-marino-1311/',
  'name': 'Vivo &#8211; Building Marino &#8211; 1311',
  'details': {'property_mls_id': '',
   'property_list_price_usd': '248888',
   'property_bedrooms': '1',
   'property_baths': '1',
   'property_total_sqft': '',
   'property_lot_m2': '',
   'property_type': 'Condos',
   'property_thumbnail_image_url': '/wp-content/uploads/2025/07/DSC00907-HDR2028129-1-150x150.jpg',
   'property_community': '',
   'is_mexhome_listing': '0',
   'property_photos': [{'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoW/40j3fctef/DSC00907-HDR%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoW/0wsg138gz/DSC00976-HDR%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoW/e7l0wmg78/DSC00736-HDR%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoW/toaqx4g2f/DSC00982-HDR%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoW/ikynpe6k5/DSC00985-HDR.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoW/somny2p4d/DSC01009-HDR.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoW/dx6ntxv6q/DSC01018-HDR%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoW/jzd2jl0ml/DSC01033-HDR%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoW/ga15qsjxu/DSC01036-HDR.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002RoW/trj1bj6gd/DSC01066-HDR.jpg'}],
   'item_location': {'lat': '15.916033',
    'lng': '-97.186544',
    'zoom': 11,
    'state': 'Oaxaca'}}},
 {'id': 718785,
  'link': 'https://mexhome.com/property/vivo-building-marino-1344/',
  'link_es': 'https://mexhome.com/es/property/vivo-building-marino-1344/',
  'name': 'Vivo &#8211; Building Marino &#8211; 1344',
  'details': {'property_mls_id': '',
   'property_list_price_usd': '360000',
   'property_bedrooms': '2',
   'property_baths': '2',
   'property_total_sqft': '',
   'property_lot_m2': '',
   'property_type': 'Condos',
   'property_thumbnail_image_url': '/wp-content/uploads/2026/01/IMG_31012028229-150x150.jpg',
   'property_community': '',
   'is_mexhome_listing': '0',
   'property_photos': [{'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rol/lik8cda1f/IMG_3101%20%282%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rol/dcweqw2jd/IMG_3076.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rol/qvblflsvl/IMG_3082%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rol/viue4r96l/IMG_3084%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rol/0mhbm4dkn/IMG_3085%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rol/lmsjmn9q6/IMG_3087%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rol/d9q7cpd85/IMG_3089.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rol/znnjro3th/IMG_3090%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rol/ltvkfiqci/IMG_3092%20%281%29.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002Rol/gk1ifbntz/IMG_3097%20%281%29.jpg'}],
   'item_location': {'lat': '15.916033',
    'lng': '-97.186544',
    'zoom': 11,
    'state': 'Oaxaca'}}},
 {'id': 719553,
  'link': 'https://mexhome.com/property/vivo-villa-lots-75/',
  'link_es': 'https://mexhome.com/es/property/vivo-villa-lots-75/',
  'name': 'Vivo &#8211; Villa Lots &#8211; 75',
  'details': {'property_mls_id': '',
   'property_list_price_usd': '135000',
   'property_bedrooms': '',
   'property_baths': '',
   'property_total_sqft': '',
   'property_lot_m2': '',
   'property_type': '',
   'property_thumbnail_image_url': '/wp-content/uploads/2026/01/Lot74-1-150x150.png',
   'property_community': '',
   'is_mexhome_listing': '0',
   'property_photos': [{'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002SXr/xbb7mydhv/Lot74.png'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002SXr/jnql1xkba/VillaAlegria_pool.jpg'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002SXr/xxtue9k3i/Clubhouse-06-01.png'}],
   'item_location': {'lat': '15.918179', 'lng': '-97.183418', 'zoom': 11}}},
 {'id': 719615,
  'link': 'https://mexhome.com/property/vivo-villa-lots-78/',
  'link_es': 'https://mexhome.com/es/property/vivo-villa-lots-78/',
  'name': 'Vivo &#8211; Villa Lots &#8211; 78',
  'details': {'property_mls_id': '',
   'property_list_price_usd': '260000',
   'property_bedrooms': '',
   'property_baths': '',
   'property_total_sqft': '',
   'property_lot_m2': '',
   'property_type': 'Land',
   'property_thumbnail_image_url': '/wp-content/uploads/2026/01/lots20-20blank20-20for20listings-150x150.png',
   'property_community': 'Vivo - Villa Lots - Mountain B',
   'is_mexhome_listing': '0',
   'property_photos': [{'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0O3i0000002SXu/rwlqyn0pq/lots%20-%20blank%20-%20for%20listings.png'}],
   'item_location': []}},
 {'id': 719617,
  'link': 'https://mexhome.com/property/vivo-villa-lots-24-2/',
  'link_es': 'https://mexhome.com/es/property/vivo-villa-lots-24-2/',
  'name': 'Vivo &#8211; Villa Lots 24',
  'details': {'property_mls_id': '',
   'property_list_price_usd': '99000',
   'property_bedrooms': '',
   'property_baths': '',
   'property_total_sqft': '',
   'property_lot_m2': '',
   'property_type': '',
   'property_thumbnail_image_url': '/wp-content/uploads/2026/01/Screenshot202026-01-2920at2012.32.08E280AFPM-150x150.png',
   'property_community': '',
   'is_mexhome_listing': '0',
   'property_photos': [{'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0OJR000005bRft/4s320vdfp/Screenshot%202026-01-29%20at%2012.32.08%E2%80%AFPM.png'},
    {'url': 'https://s3.amazonaws.com/propertybase-clients/00D3i000000vOqYEAU/a0OJR000005bRft/6t54y9e63/Lot%2024%20image.png'}],
   'item_location': []}},
 {'id': 720853,
  'link': 'https://mexhome.com/property/vivo-building-l-1223/',
  'link_es': 'https://mexhome.com/es/property/vivo-building-l-1223/',
  'name': 'Vivo &#8211; Building L &#8211; 1223',
  'details': {'property_mls_id': '',
   'property_list_price_usd': '372000',
   'property_bedrooms': '2',
   'property_baths': '2',
   'property_total_sqft': '',
   'property_lot_m2': '',
   'property_type': 'Condos',
   'property_community': '',
   'is_mexhome_listing': '0',
   'property_photos': [],
   'item_location': []}},
 {'id': 721487,
  'link': 'https://mexhome.com/property/vivo-building-h-843/',
  'link_es': 'https://mexhome.com/es/property/vivo-building-h-843/',
  'name': 'Vivo &#8211; Building H &#8211; 843',
  'details': {'property_mls_id': '',
   'property_list_price_usd': '499000',
   'property_bedrooms': '4',
   'property_baths': '3',
   'property_total_sqft': '',
   'property_lot_m2': '',
   'property_type': 'Condos',
   'property_thumbnail_image_url': '/wp-content/uploads/2026/02/IMG_6937-2-150x150.jpg',
   'property_community': '',
   'is_mexhome_listing': '0',

In [39]:
#Obtener los datos

oferta=[]
precio=[]
cuartos=[]
banos=[]
latitud=[]
longitud=[]
metros_cuad_const=[]
metros_cuad_terreno=[]
tipo=[]
for propiedades in data:
    oferta.append(propiedades.get('name'))
    precio.append(propiedades.get('details', {}).get('property_list_price_usd'))
    cuartos.append(propiedades.get('details', {}).get('property_bedrooms'))
    banos.append(propiedades.get('details', {}).get('property_baths'))
    metros_cuad_const.append(propiedades.get('details', {}).get('property_lot_m2'))
    metros_cuad_terreno.append(propiedades.get('details', {}).get('property_total_sqft'))

    latitud.append(
    float(((propiedades.get('details') if isinstance(propiedades.get('details'), dict) else {}).get('item_location') or {}).get('lat'))
    if ((propiedades.get('details') if isinstance(propiedades.get('details'), dict) else {}).get('item_location') or {}).get('lat')
    else None
    )
    longitud.append(float(((propiedades.get('details') if isinstance(propiedades.get('details'), dict) else {}).get('item_location') or {}).get('lng'))
     if ((propiedades.get('details') if isinstance(propiedades.get('details'), dict) else {}).get('item_location') or {}).get('lng')
     else None)
    tipo.append(propiedades.get('details', {}).get('property_type'))

mexhome_df=pd.DataFrame({'oferta':oferta,'precio':precio,'moneda':'USD',
                         'cuartos':cuartos,
                         'metros_cuad_const':metros_cuad_const,
                            'metros_cuad_terreno':metros_cuad_terreno,
                         'banos':banos,'latitud':latitud,'longitud':longitud,
                         'tipo':tipo, "fuente":"mexhome","fecha_consulta":pd.Timestamp.now()})
mexhome_df.head(5)

,oferta,precio,moneda,cuartos,metros_cuad_const,metros_cuad_terreno,banos,latitud,longitud,tipo,fuente,fecha_consulta
0,Vivo &#8211; Building F &#8211; 632,295000,USD,2,,,2,NaN,NaN,Condos,mexhome,2026-03-30 00:59:00.382707
1,Vivo &#8211; Building H &#8211; 833,685000,USD,4,,,3,15.915630,-97.185896,Condos,mexhome,2026-03-30 00:59:00.382707
2,Vivo &#8211; Villa Lots &#8211; 28,149000,USD,,,,,15.915738,-97.182546,Land,mexhome,2026-03-30 00:59:00.382707
3,325 Vivo &#8211; Building C,128900,USD,0,,,1,NaN,NaN,Condos,mexhome,2026-03-30 00:59:00.382707
4,Vivo &#8211; Building E &#8211; 531,425000,USD,3,,,2,15.915336,-97.185159,Condos,mexhome,2026-03-30 00:59:00.382707

#### OsanPuerto

In [40]:
url = "https://www.osanpuerto.com/modules/mod_properties/request.php"

headers = {
    "accept": "application/json, text/javascript, */*; q=0.01",
    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
    "x-requested-with": "XMLHttpRequest",
    "referer": "https://www.osanpuerto.com/",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

data = {
    "lang": "_es",
    "type": "",
    "action": "get_properties",
    "status": "",
    "price": "",
    "currency": "",
    "q": ""
}

response = requests.post(url, headers=headers, data=data)

# Validación básica
response.raise_for_status()

json_data = response.json()

osanpuerto = pd.DataFrame(json_data["data"])
#Seleccionar name, currency, type, lat, lng
osanpuerto = osanpuerto[["name","bathrooms","bedrooms","swimming_pool","parking","price","currency", "type", "lat", "lng", "m2"]]
#Renombrar columnas
osanpuerto.rename(columns={
    "name": "oferta",
    "bathrooms": "banos",
    "bedrooms": "cuartos",
    "swimming_pool": "piscina",
    "parking": "estacionamiento",
    "price": "precio",
    "currency": "moneda",
    "type": "tipo",
    "lat": "latitud",
    "lng": "longitud",
    "m2": "metros_cuad_terreno"
}, inplace=True)

#Añadir fuente y fecha de consulta
osanpuerto["fuente"] = "osanpuerto"
osanpuerto["fecha_consulta"] = pd.Timestamp.now()

osanpuerto.head(5)

,oferta,banos,cuartos,piscina,estacionamiento,precio,moneda,tipo,latitud,longitud,metros_cuad_terreno,fuente,fecha_consulta
0,"Terreno en Venta en Punta Zicatela, Puerto Esc...",0,0,0,0,11600000.00,MXN,Terreno,15.84191670000000,-97.04775000000000,827.94,osanpuerto,2026-03-30 00:59:01.284736
1,"One Pacific Rinconada, Exclusivos Departamento...",1,1,1,1,2652400.00,MXN,Departamento,15.86236337608092,-97.07494115333918,43,osanpuerto,2026-03-30 00:59:01.284736
2,Preventa | Desarrollo Boutique Selva Blanca,1,1,0,1,2350000.00,MXN,Departamento,15.84477780000000,-97.04830560000000,44.4,osanpuerto,2026-03-30 00:59:01.284736
3,Casa con Vista al Mar en Esperanza Verde con D...,3,3,1,0,550000.00,USD,Casa,15.88214680619166,-97.10321065678605,300,osanpuerto,2026-03-30 00:59:01.284736
4,Condominios exclusivos cerca de la playa en Pu...,2,2,1,1,388000.00,USD,Departamento,15.82255000000000,-97.03642000000000,160,osanpuerto,2026-03-30 00:59:01.284736

#### RealEstate.PuertoEscondido

In [41]:
url = "https://realestate.puerto-escondido.mx/es/propiedades/"

headers = {
    "User-Agent": "Mozilla/5.0"
}

html = requests.get(url, headers=headers).text

# =========================
# EXTRAER markers
# =========================
pattern = r'googlecode_regular_vars\.markers="(\[\[.*?\]\])"'

match = re.search(pattern, html, re.DOTALL)
markers_raw = match.group(1)

markers_raw = markers_raw.replace('\\"', '"')
markers = json.loads(markers_raw)

# =========================
# PARSEAR
# =========================
rows = []

for m in markers:
    try:
        nombre = m[0]
        lat = float(m[1])
        lon = float(m[2])

        # precio
        precio = float(m[11]) if m[11] else None

        # tipo
        tipo = m[15] if len(m) > 15 else None

        # cuartos (posición 12)
        try:
            cuartos = int(m[12])
        except:
            cuartos = None

        # baños (posición 13)
        try:
            banos = int(m[13])
        except:
            banos = None

        rows.append({
            "oferta": nombre,
            "latitud": lat,
            "longitud": lon,
            "precio": precio,
            "tipo": tipo,
            "cuartos": cuartos,
            "banos": banos
        })

    except Exception as e:
        print("error:", e)

# =========================
# DATAFRAME
# =========================
realestatepuerto = pd.DataFrame(rows)

realestatepuerto["moneda"] = "MXN"
realestatepuerto["fuente"] = "realestate_puerto_escondido"
realestatepuerto["fecha_consulta"] = datetime.now()

# limpiar nombre
realestatepuerto["oferta"] = realestatepuerto["oferta"].apply(requests.utils.unquote)

print("Total registros:", len(realestatepuerto))
realestatepuerto.head()

Total registros: 180

,oferta,latitud,longitud,precio,tipo,cuartos,banos,moneda,fuente,fecha_consulta
0,Casa ecológica única en La Punta,15.836159,-97.043481,12480000.0,Casa,2,2.0,MXN,realestate_puerto_escondido,2026-03-30 00:59:01.978870
1,Propiedad Frente al Mar de Lujo en El Puertecito,15.740076,-96.855683,28305984.0,Casa,11,NaN,MXN,realestate_puerto_escondido,2026-03-30 00:59:01.978870
2,Lotes Frente al Mar en Palmarito,15.916446,-97.186960,7710000.0,Terreno,0,0.0,MXN,realestate_puerto_escondido,2026-03-30 00:59:01.978870
3,Terreno con Vista al Mar en Agua Blanca,15.734264,-96.812565,1750000.0,Terreno,0,0.0,MXN,realestate_puerto_escondido,2026-03-30 00:59:01.978870
4,Propiedad con Negocio Vacacional Operando en L...,15.837838,-97.044241,24000000.0,Casa,8,8.0,MXN,realestate_puerto_escondido,2026-03-30 00:59:01.978870

#### Century21

In [42]:
URL = "https://century21mexico.com/busqueda/en-estado_oaxaca/en-municipio_san-pedro-mixtepec-juquila/en-colonia_san-pedro-mixtepec-juquila-puerto-escondido"

# ==============================
# DRIVER
# ==============================
options = Options()
options.add_argument("--headless=new")
options.add_argument("--window-size=1920,1080")

driver = webdriver.Chrome(options=options)
wait = WebDriverWait(driver, 20)

driver.get(URL)

# esperar a que rendericen las cards reales
wait.until(
    EC.presence_of_element_located(
        (By.CSS_SELECTOR, "div.card.mb-4.shadow")
    )
)

time.sleep(2)

# ==============================
# HTML RENDERIZADO
# ==============================
html = driver.page_source
driver.quit()

# ==============================
# PARSEAR HTML
# ==============================
soup = BeautifulSoup(html, "html.parser")

cards = soup.select("div.card.mb-4.shadow")

rows = []

for card in cards:
    # --------------------------
    # titulo
    # --------------------------
    titulo_tag = card.select_one("h5.card-title")
    titulo = titulo_tag.get_text(" ", strip=True) if titulo_tag else None

    # --------------------------
    # precio
    # --------------------------
    precio = None
    texto_card = card.get_text(" ", strip=True)

    m_precio = re.search(r"\$[\d,]+(?:\.\d+)?\s*MXN", texto_card)
    if m_precio:
        precio_txt = m_precio.group(0)
        precio = float(
            precio_txt.replace("$", "")
                      .replace(",", "")
                      .replace("MXN", "")
                      .strip()
        )

    # --------------------------
    # m² terreno y construcción
    # --------------------------
    metros_cuad_terreno = None
    metros_cuad_const = None

    m_terreno = re.search(r"([\d,]+)\s*m²T", texto_card)
    m_const   = re.search(r"([\d,]+)\s*m²C", texto_card)

    if m_terreno:
        metros_cuad_terreno = float(m_terreno.group(1).replace(",", ""))

    if m_const:
        metros_cuad_const = float(m_const.group(1).replace(",", ""))

    rows.append({
        "oferta": titulo,
        "precio": precio,
        "metros_cuad_terreno": metros_cuad_terreno,
        "metros_cuad_const": metros_cuad_const
    })

century21 = pd.DataFrame(rows)
#Añadir hora de consulta
century21["fecha_consulta"] = pd.Timestamp.now()
#Añadir fuente 
century21["fuente"] = "century21_mexico"
century21["moneda"] = "MXN"
century21.head()

,oferta,precio,metros_cuad_terreno,metros_cuad_const,fecha_consulta,fuente,moneda
0,En venta - Terreno en venta en Puerto Escondid...,9574230.0,1126.0,0.0,2026-03-30 00:59:11.007481,century21_mexico,MXN
1,En venta - Terreno en venta en Puerto Escondid...,8514110.0,1002.0,0.0,2026-03-30 00:59:11.007481,century21_mexico,MXN

#### Grupo Escondido PXM

In [43]:
url = "https://www.grupoescondidopxm.mx/propiedades"

# ==============================
# DESCARGAR HTML Y LEER JSON WIX
# ==============================
html = requests.get(url).text
soup = BeautifulSoup(html, "html.parser")

script = soup.find("script", {"id": "wix-warmup-data"})
data = json.loads(script.string)

updates = data["platform"]["ssrPropsUpdates"]

# ==============================
# REPEATER UI
# ==============================
items = updates[0]["comp-maldqg5c"]["items"]

flat = {}
for d in updates[1:]:
    flat.update(d)

# ==============================
# BUSCAR DATA REAL POR item_id
# ==============================
def buscar_por_item_id(obj, item_id):
    """
    Busca recursivamente un diccionario cuyo key sea exactamente item_id.
    """
    if isinstance(obj, dict):
        for k, v in obj.items():
            if k == item_id and isinstance(v, dict):
                return v

            found = buscar_por_item_id(v, item_id)
            if found is not None:
                return found

    elif isinstance(obj, list):
        for v in obj:
            found = buscar_por_item_id(v, item_id)
            if found is not None:
                return found

    return None


# ==============================
# HELPER PARA georeferencedLocation
# ==============================
def parse_geo(geo):
    lat, lon = None, None

    if not geo:
        return lat, lon

    if isinstance(geo, str):
        try:
            lat, lon = map(float, geo.split(","))
        except:
            pass

    elif isinstance(geo, dict):
        try:
            lat = float(geo.get("latitude")) if geo.get("latitude") is not None else None
            lon = float(geo.get("longitude")) if geo.get("longitude") is not None else None
        except:
            lat, lon = None, None

    return lat, lon


# ==============================
# EXTRAER TABLA
# ==============================
rows = []

for item_id in items:

    # -------- titulo --------
    titulo_html = flat.get(f"comp-maldqg68__{item_id}", {}).get("html", "")
    titulo = BeautifulSoup(titulo_html, "html.parser").get_text(strip=True)

    # -------- precio --------
    precio_html = flat.get(f"comp-maldqg6l1__{item_id}", {}).get("html", "")
    precio_txt = BeautifulSoup(precio_html, "html.parser").get_text(strip=True)
    precio = float(re.sub(r"[^\d]", "", precio_txt)) if precio_txt else None

    # -------- data real exacta por item_id --------
    real = buscar_por_item_id(data, item_id)

    lat = lon = area = None

    if isinstance(real, dict):
        lat, lon = parse_geo(real.get("georeferencedLocation"))
        area = real.get("totalArea")

        # fallback por si viniera en location
        if (lat is None or lon is None) and isinstance(real.get("location"), dict):
            try:
                lat = float(real["location"].get("latitude")) if real["location"].get("latitude") is not None else lat
                lon = float(real["location"].get("longitude")) if real["location"].get("longitude") is not None else lon
            except:
                pass

    rows.append({
        
        "oferta": titulo,
        "precio": precio,
        "latitud": lat,
        "longitud": lon,
        "metros_cuad_terreno": area
    })

pxm = pd.DataFrame(rows)
#Añadir hora de consulta
pxm["fecha_consulta"] = pd.Timestamp.now()
#Añadir fuente 
pxm["fuente"] = "grupo escondido pxm"
pxm["moneda"] = "MXN"

#### Pincali

In [44]:
def scrape_pincali():
    
    # -----------------------------
    # Consultation date
    # -----------------------------
    consultation_date = datetime.now()
    
    # -----------------------------
    # Operation mapping
    # -----------------------------
    
    all_tables = []

    # -----------------------------
    # Loop pages
    # -----------------------------
    for i in tqdm(range(1, 5), desc="Scrapeando Pincali"):
        
        # -----------------------------
        # URL
        # -----------------------------
        url = f"https://www.pincali.com/inmuebles/propiedades-en-venta?geolocation=%255B%255B14.89015257266123%252C%2520-96.7086217718429%255D%252C%2520%255B15.938592100304156%252C%2520-95.75770589646189%255D%255D&page={i}"
        
        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, "html.parser")
        
        basic_data = soup.find_all("li", class_="property__component")
        
        # -----------------------------
        # Lists of data
        # -----------------------------
        name, bedrooms, bathrooms, latitude, longitude, street, region, locality, price, surface = [], [], [], [], [], [], [], [], [], []
        
        # -----------------------------
        # Loop through each property and extract data
        # -----------------------------
        for elementos in basic_data:
            
            price_tag = elementos.find("li", class_="price")
            price.append(price_tag.get_text(strip=True) if price_tag else None)
            
            name_tag = elementos.find("div", class_="title")
            name.append(name_tag.get_text(strip=True) if name_tag else None)
            
            lat = elementos.get("data-lat")
            lng = elementos.get("data-long")
            
            latitude.append(float(lat) if lat else None)
            longitude.append(float(lng) if lng else None)
            
            location_tag = elementos.find("div", class_="location")
            
            if location_tag:
                location_text = location_tag.get_text(strip=True)
                street.append(location_text)
                
                partes = [p.strip() for p in location_text.split(",")]
                locality.append(partes[-1] if len(partes) > 0 else None)
                region.append(partes[-2] if len(partes) > 1 else None)
            else:
                street.append(None)
                region.append(None)
                locality.append(None)
            
            rec = None
            bath = None
            sup = None
            
            features = elementos.find("div", class_="features")
            
            if features:
                for item in features.find_all("div"):
                    texto = item.get_text(strip=True).lower()
                    
                    numero = re.search(r"\d+", texto)
                    numero = int(numero.group()) if numero else None
                    
                    if "rec" in texto:
                        rec = numero
                    elif "bañ" in texto:
                        bath = numero
                    elif "m²" in texto or "m2" in texto:
                        sup = numero
            
            bedrooms.append(rec)
            bathrooms.append(bath)
            surface.append(sup)
            
        
        # -----------------------------
        # DataFrame for page
        # -----------------------------
        table = pd.DataFrame({
            "oferta": name,
            "precio": price,
            "metros_cuad_const": surface,
            "cuartos": bedrooms,
            "banos": bathrooms,
            "latitud": latitude,
            "longitud": longitude,
            "fecha_consulta": consultation_date
        })
        
        all_tables.append(table)

    # -----------------------------
    # Final DataFrame
    # -----------------------------
    table = pd.concat(all_tables, ignore_index=True)
    table["fuente"] = "Pincali"
    table["moneda"] = table["precio"].str.extract(r"(MXN|USD)")
    table["precio"] = (
    table["precio"]
    .str.replace(r"[^\d.,]", "", regex=True)   # quita letras y símbolos
    .str.replace(",", "")                     # quita comas de miles
    .astype(float)
)
    
    return table

In [45]:
pincali_data= scrape_pincali()
print("Total registros:", len(pincali_data))
pincali_data.head()

Scrapeando Pincali: 100%|██████████| 4/4 [00:03<00:00,  1.06it/s]

Total registros: 151

,oferta,precio,metros_cuad_const,cuartos,banos,latitud,longitud,fecha_consulta,fuente,moneda
0,Finca Cafetalera en Venta! Alto Potencial Agro...,180000.0,NaN,NaN,NaN,15.917291,-96.175926,2026-03-30 00:59:11.832144,Pincali,MXN
1,VENTA DEPARTAMENTOS CERCA DE LA PLAYA EN HUATU...,5541000.0,97.0,2.0,1.0,15.834007,-96.319949,2026-03-30 00:59:11.832144,Pincali,MXN
2,"Villa con vista al mar en Zipolite, Oaxaca, co...",300000.0,125.0,1.0,1.0,15.664205,-96.516655,2026-03-30 00:59:11.832144,Pincali,USD
3,Casa de 2 habitaciones con vista al océano en ...,385000.0,180.0,2.0,3.0,15.663782,-96.516925,2026-03-30 00:59:11.832144,Pincali,USD
4,Villa de 4 habitaciones con vista al océano en...,595000.0,267.0,4.0,5.0,15.664334,-96.516689,2026-03-30 00:59:11.832144,Pincali,USD

#### Gr8 Real Estate

In [46]:
url = "https://gr8-realestate.com/azul-escondido/"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

html = requests.get(url, headers=headers).text
soup = BeautifulSoup(html, "html.parser")

# =========================
# 1. NOMBRE Y PRECIO
# =========================
nombre, precio = None, None

for script in soup.find_all("script", {"type": "application/ld+json"}):
    try:
        data = json.loads(script.text)
        if "@graph" in data:
            for item in data["@graph"]:
                if item.get("@type") == "WebPage":
                    nombre = item.get("name")
                    desc = item.get("description", "")
                    m = re.search(r"\$([\d,]+)", desc)
                    if m:
                        precio = int(m.group(1).replace(",", ""))
    except:
        pass

# =========================
# 2. IFRAME Y COORDENADAS
# =========================
iframe = soup.find("iframe", src=lambda x: x and "maps.google.com" in x)

if iframe is None:
    raise ValueError("No se encontró iframe de Google Maps")

src = iframe["src"]

# Realizamos el request a la URL del iframe para obtener el JS interno
iframe_html = requests.get(src, headers=headers).text

# Extraemos las coordenadas usando el patrón [latitud, longitud] que vimos en el response text
# Buscamos el patrón de números decimales dentro de corchetes
match = re.search(r'\[(-?\d+\.\d+),(-?\d+\.\d+)\]', iframe_html)

if match:
    lat = float(match.group(1))
    lon = float(match.group(2))
else:
    lat, lon = None, None

# =========================
# 6. DF FINAL
# =========================
gr8 = pd.DataFrame([{
    "oferta": nombre,
    "precio": precio,
    "latitud": lat,
    "longitud": lon
}])

#Añadir fuente y fecha de consulta
gr8["fuente"] = "gr8_realestate"
gr8["fecha_consulta"] = pd.Timestamp.now()
gr8["moneda"] = "MXN"
gr8

,oferta,precio,latitud,longitud,fuente,fecha_consulta,moneda
0,Azul Escondido Terrenos en Preventa en Puerto ...,780000,15.799661,-96.943204,gr8_realestate,2026-03-30 00:59:17.172339,MXN

In [47]:
# ===================================
# CONFIG
# ===================================
options = Options()
options.add_argument("--headless=new")
options.add_argument("user-agent=Mozilla/5.0")

driver = webdriver.Chrome(options=options)

url = "https://www.matronarealestate.com/"
driver.get(url)

time.sleep(5)

rows = []

# ===================================
# SOLO HEADERS QUE SON PROYECTOS
# ===================================
titulos = driver.find_elements(By.XPATH, "//h1 | //h2 | //h3")

for t in titulos:
    nombre = t.text.strip()

    # 🔥 filtro clave
    if not nombre.lower().startswith("residencial"):
        continue

    try:
        ul = t.find_element(By.XPATH, "following::ul[1]")
        items = ul.find_elements(By.TAG_NAME, "li")

        for item in items:
            texto = item.text.strip()

            if "$" in texto:
                rows.append({
                    "oferta": nombre,
                    "detalle": texto
                })

    except:
        continue

driver.quit()

matrona= pd.DataFrame(rows).drop_duplicates()
#Añadir fuente y fecha de consulta
matrona["fuente"] = "Matrona Real Estate"
matrona["fecha_consulta"] = pd.Timestamp.now()
matrona["moneda"] = "MXN"
matrona.head()

,oferta,detalle,fuente,fecha_consulta,moneda
0,Residencial Punta Lago,"Precios desde $6,000 x m2",Matrona Real Estate,2026-03-30 01:00:11.838095,MXN
1,Residencial Zelena,"Precios desde $4,000 x m2",Matrona Real Estate,2026-03-30 01:00:11.838095,MXN
2,Residencial Aman,"Lotes de 200m desde $500,000",Matrona Real Estate,2026-03-30 01:00:11.838095,MXN

#### Puerto Property

In [48]:
url="https://puertoproperty.com/portofolio/"
r=requests.get(url, headers=headers)
soup=BeautifulSoup(r.text, "html.parser")
tabla=soup.find("table")
filas=tabla.find_all("tr")
rows = []
for fila in filas[1:]:
    celdas = fila.find_all("td")
    
    if len(celdas) >= 4:
        oferta = celdas[0].get_text(strip=True)
        detalle = celdas[1].get_text(strip=True)
        
        size = celdas[2].get_text(strip=True)
        price = celdas[3].get_text(strip=True)
        
        # limpiar números
        size = float(size.replace(",", "")) if size else None
        price = float(price.replace(",", "")) if price else None

        rows.append({
            "oferta": oferta,
            "detalle": detalle,
            "metros_cuad_const": size,
            "precio": price
        })

puertoproperty = pd.DataFrame(rows)

# metadatos
puertoproperty["fuente"] = "Puerto Property"
puertoproperty["fecha_consulta"] = pd.Timestamp.now()
puertoproperty["moneda"] = "USD"

puertoproperty.head()

,oferta,detalle,metros_cuad_const,precio,fuente,fecha_consulta,moneda
0,12a,Sold,1739.07,521721.0,Puerto Property,2026-03-30 01:00:12.522575,USD
1,13a,Sold,1747.90,524370.0,Puerto Property,2026-03-30 01:00:12.522575,USD
2,34,Sold,1971.40,591420.0,Puerto Property,2026-03-30 01:00:12.522575,USD
3,35,Sold,1834.63,550389.0,Puerto Property,2026-03-30 01:00:12.522575,USD
4,36,Sold,1814.27,544281.0,Puerto Property,2026-03-30 01:00:12.522575,USD

#### Inmobisur

In [49]:
url = "https://inmobisur.mx/#desarrollos"
headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers)
response.encoding = 'utf-8' 
soup = BeautifulSoup(response.text, "html.parser")

bloques = soup.find_all("div", {"data-framer-component-type": "RichTextContainer"})
data = []

for bloque in bloques:
    texto = bloque.get_text(separator="\n").strip()
    
    if "Plusvalía" in texto or "lotes" in texto:
        # Unimos todo para facilitar la búsqueda con regex
        limpio = " ".join([l.strip() for l in texto.split('\n') if l.strip()])
        
        # 1. Tiempo: Buscamos solo el número y la unidad (meses/semanas)
        # Captura: un número y la palabra que le sigue inmediatamente
        tiempo_match = re.search(r'comercialización:\s*(\d+\s*(?:meses|semanas|mes))', limpio, re.I)
        
        # 2. Metros cuadrados: Buscamos el patrón de m²
        # Algunos tienen dos valores (total | comercializado), capturamos el bloque numérico
        m2_match = re.search(r'([\d,]+\s*(?:\|\s*[\d,]+\s*)?m²)', limpio)
        
        # 3. Plusvalía, Lotes e Inversionistas (reutilizados)
        plusvalia_match = re.search(r'Plusvalía:\s*([\d\–\-%\s]+)', limpio)
        lotes_match = re.search(r'(\d+)\s*lotes', limpio)
        inv_match = re.search(r'(\d+)\s*inversionistas', limpio)

        lineas = texto.split('\n')
        registro = {
            "oferta": lineas[0].strip(),
            "ubicacion": lineas[1].strip() if len(lineas) > 1 else None,
            "metros_cuad_terreno": m2_match.group(1).replace('m²', '').strip() if m2_match else None,
            "lotes": lotes_match.group(1) if lotes_match else None,
            "inversionistas": inv_match.group(1) if inv_match else None,
            "plusvalia": plusvalia_match.group(1).strip() if plusvalia_match else None,
            "tiempo_comercializacion": tiempo_match.group(1) if tiempo_match else None
        }
        data.append(registro)

inmobisur = pd.DataFrame(data).drop_duplicates(subset=['oferta', 'ubicacion']).reset_index(drop=True)
#Añadir fuente y fecha de consulta
inmobisur["fuente"] = "Inmobisur"
inmobisur["fecha_consulta"] = pd.Timestamp.now()
inmobisur.head()

,oferta,ubicacion,metros_cuad_terreno,lotes,inversionistas,plusvalia,tiempo_comercializacion,fuente,fecha_consulta
0,2019 - ÍNDIGO Residencial,"Puertecito, Santa María Colotepec","9,185",36,30,20%,2 meses,Inmobisur,2026-03-30 01:00:20.317678
1,2020 - CIAN Residencial,Santa María Colotepec,"29,996",96,70,25%,2 meses,Inmobisur,2026-03-30 01:00:20.317678
2,2021 - AQUA Residencial I,"Agua Blanca, Santa María Colotepe","25,467 | 21,091",90,70,23–24 %,3 semanas,Inmobisur,2026-03-30 01:00:20.317678
3,2019 - ÍNDIGO Residencial,"Puertecito, Santa María Colotepec","9,185",36,30,20%,2 meses,Inmobisur,2026-03-30 01:00:20.317678
4,2021 - TEAL Residencial,"Agua Blanca, Santa María Tonameca","4,299 | 38,119",192,125,14,13 meses,Inmobisur,2026-03-30 01:00:20.317678

#### Madre Ceiba

In [50]:
#No usar headless 
options = Options()
driver = webdriver.Chrome(options=options)

try:
    driver.get("https://www.madreceibaproperties.com/es/propiedades")
    time.sleep(4) # Espera a que cargue la primera tanda

    # --- ESTRATEGIA DE SCROLL POR ETAPAS ---
    registros_actuales = 0
    intentos_sin_cambio = 0
    
    while True:
        # Bajamos un poco (ejemplo: 1000 pixeles)
        driver.execute_script("window.scrollBy(0, 1000);")
        time.sleep(1.5) # Pausa breve para que el JS reaccione
        
        # Contamos cuántas tarjetas hay en el DOM en este momento
        soup_temp = BeautifulSoup(driver.page_source, "html.parser")
        conteo = len(soup_temp.find_all("div", class_="destacados_title-wrapper"))
        
        print(f"Cargados hasta ahora: {conteo} registros...")

        if conteo > registros_actuales:
            registros_actuales = conteo
            intentos_sin_cambio = 0
        else:
            intentos_sin_cambio += 1
            # Si después de 8 scrolls no sube el número, ya llegamos al final real
            if intentos_sin_cambio > 8: 
                break

    # --- EXTRACCIÓN FINAL ---
    final_soup = BeautifulSoup(driver.page_source, "html.parser")
    resultados = final_soup.find_all("div", class_="destacados_title-wrapper")

    lista_propiedades = []
    for res in resultados:
        # Tu lógica de extracción corregida
        ubicacion = res.find("div", attrs={"fs-list-field": "ubicacion"})
        precio = res.find("div", class_="text-group")
        titulo = res.find("h3")
        tipo = res.find("div", attrs={"fs-list-field": "propiedad"}) 
        superficie_terreno = res.find("div", attrs={"fs-list-field": "superficie"})
        superficie_construccion = res.find("div", attrs={"fs-list-field": "construccion"})
        cuartos = res.find("div", attrs={"fs-list-field": "recamaras"})

        lista_propiedades.append({
            "ubicacion": ubicacion.get_text(strip=True) if ubicacion else None,
            "precio": precio.get_text(strip=True) if precio else None,
            "oferta": titulo.get_text(strip=True) if titulo else None,
            "tipo": tipo.get_text(strip=True) if tipo else None,
            "metros_cuad_terreno": superficie_terreno.get_text(strip=True) if superficie_terreno else None,
            "metros_cuad_const": superficie_construccion.get_text(strip=True) if superficie_construccion else None,
            "cuartos": cuartos.get_text(strip=True) if cuartos else None
        })

    madre_ceiba = pd.DataFrame(lista_propiedades)
    
    # Limpieza final
    madre_ceiba['precio'] = madre_ceiba['precio'].str.replace(r'[^\d]', '', regex=True)
    madre_ceiba['precio'] = pd.to_numeric(madre_ceiba['precio'], errors='coerce')

finally:
    driver.quit()

print("Total de registros extraídos:", len(madre_ceiba))
#Añadir fuente y fecha de consulta
madre_ceiba["fuente"] = "Madre Ceiba Properties"
madre_ceiba["fecha_consulta"] = pd.Timestamp.now()
madre_ceiba["moneda"] = "MXN"
madre_ceiba.head()

Cargados hasta ahora: 20 registros...
Cargados hasta ahora: 20 registros...
Cargados hasta ahora: 20 registros...
Cargados hasta ahora: 20 registros...
Cargados hasta ahora: 40 registros...
Cargados hasta ahora: 40 registros...
Cargados hasta ahora: 40 registros...
Cargados hasta ahora: 40 registros...
Cargados hasta ahora: 40 registros...
Cargados hasta ahora: 60 registros...
Cargados hasta ahora: 60 registros...
Cargados hasta ahora: 60 registros...
Cargados hasta ahora: 60 registros...
Cargados hasta ahora: 80 registros...
Cargados hasta ahora: 80 registros...
Cargados hasta ahora: 80 registros...
Cargados hasta ahora: 80 registros...
Cargados hasta ahora: 80 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Total de registros extraídos: 97

,ubicacion,precio,oferta,tipo,metros_cuad_terreno,metros_cuad_const,cuartos,fuente,fecha_consulta,moneda
0,Barra de Colotepec,1450000,Terreno Lomas de La Barra,Terreno,400,None,,Madre Ceiba Properties,2026-03-30 01:01:17.912926,MXN
1,Barra de Colotepec,1900000,Terreno a unos pasos del mar,Terreno,200,None,,Madre Ceiba Properties,2026-03-30 01:01:17.912926,MXN
2,Barra de Navidad,500000,Terreno Barra de Navidad,Terreno,200,None,,Madre Ceiba Properties,2026-03-30 01:01:17.912926,MXN
3,Lindavista,1900000,Terreno Lindavista,Terreno,250,None,,Madre Ceiba Properties,2026-03-30 01:01:17.912926,MXN
4,San Pedro Mixtepec,22000000,Casa en Construcción en Palmarito,Casa,1200,None,3,Madre Ceiba Properties,2026-03-30 01:01:17.912926,MXN

#### Viva México Inmobiliaria

In [51]:
# 1. Definimos la lista de fuentes con su respectivo tipo
fuentes = [
    {"url": "https://www.vivamexicoinmobiliaria.com/casas-departamentos-en-venta-puerto-escondido/", "tipo": "casas y departamentos"},
    {"url": "https://www.vivamexicoinmobiliaria.com/terrenos-en-venta-puerto-escondido/", "tipo": "terrenos"},
    {"url": "https://www.vivamexicoinmobiliaria.com/desarrollos-en-puerto-escondido/", "tipo": "desarrollos"}
]

headers = {"User-Agent": "Mozilla/5.0"}
rows = []

# 2. Iteramos sobre cada fuente
for fuente in fuentes:
    r = requests.get(fuente["url"], headers=headers)
    soup = BeautifulSoup(r.text, "html.parser")
    
    # Buscamos los contenedores
    resultados = soup.find_all("div", class_="elementor-widget-wrap elementor-element-populated")

    for res in resultados:
        titulo_tag = res.find("h2", class_="elementor-heading-title elementor-size-default")
        precio_tag = res.find("span", class_="woocommerce-Price-amount amount")
        detalle = res.find("div", class_="elementor-element elementor-element-05e92d1 elementor-widget elementor-widget-text-editor")
        
        if titulo_tag and precio_tag:
            rows.append({
                "oferta": titulo_tag.get_text(strip=True),
                "precio": precio_tag.get_text(strip=True),
                "detalle": detalle.get_text(separator=" ", strip=True) if detalle else "",
                "tipo": fuente["tipo"]  
            })

# 3. Creación del DataFrame y limpieza
vivamexico = pd.DataFrame(rows)

# Eliminar duplicados considerando el tipo por si una oferta aparece en dos categorías
vivamexico = vivamexico.drop_duplicates(subset=['oferta', 'precio', 'tipo']).reset_index(drop=True)

# Añadir metadatos
vivamexico["fuente"] = "Viva Mexico Inmobiliaria"
vivamexico["fecha_consulta"] = pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S")

print(f"Total de registros capturados: {len(vivamexico)}")
#Eliminar símbolos de precio y convertir a numérico
vivamexico['precio'] = vivamexico['precio'].str.replace(r'[^\d.]', '', regex=True)
vivamexico['precio'] = pd.to_numeric(vivamexico['precio'], errors='coerce')
vivamexico.head()

Total de registros capturados: 73

,oferta,precio,detalle,tipo,fuente,fecha_consulta
0,"Casa en Residencial Don Goyo, Punta Zicatela",8800000.0,"Villa Bombon, Una propiedad de gran tamaño y u...",casas y departamentos,Viva Mexico Inmobiliaria,2026-03-30 01:01:19
1,"Casa Selva Mar, Playa San Agustinillo, Oaxaca",5500000.0,"Ideal como casa de descanso, residencia perman...",casas y departamentos,Viva Mexico Inmobiliaria,2026-03-30 01:01:19
2,"Departamento Altavista– Vista al mar, diseño y...",309000.0,Altavista se encuentra en una zona en constant...,casas y departamentos,Viva Mexico Inmobiliaria,2026-03-30 01:01:19
3,"Casa El Faro, Puerto Angel",13500000.0,Casa del Faro – Residencia con vista infinita ...,casas y departamentos,Viva Mexico Inmobiliaria,2026-03-30 01:01:19
4,"Casa frente al mar en Playa Delfines, Puerto E...",2300000.0,"Casa de lujo frente al mar en Playa Delfines, ...",casas y departamentos,Viva Mexico Inmobiliaria,2026-03-30 01:01:19

In [53]:
url="https://grupoinmobiliariohersa.com/terrenos-en-venta"
r=requests.get(url, headers=headers)
soup=BeautifulSoup(r.text, "html.parser")

In [54]:
titulos = [t.get_text(strip=True) for t in soup.find_all("h4", attrs={"data-typography": "HeadingBeta"})]
precios = [p.get_text(strip=True) for p in soup.find_all("div", attrs={"data-ux": "Price"})]
#Crear DataFrame
hersa = pd.DataFrame({
    "oferta": titulos,
    "precio": precios
})
#Añadir fuente y fecha de consulta
hersa["fuente"] = "Hersa"
hersa["fecha_consulta"] = pd.Timestamp.now()
hersa["moneda"] = "MXN"
#Limpiar precio
hersa['precio'] = hersa['precio'].str.replace(r'[^\d.]', '', regex=True)
hersa

,oferta,precio,fuente,fecha_consulta,moneda
0,Fraccionamiento El Mirador,380000.00,Hersa,2026-03-30 01:02:37.813903,MXN
1,Fraccionamiento El Guaje,150000.00,Hersa,2026-03-30 01:02:37.813903,MXN
2,Fraccionamiento Los Frutillos,250000.00,Hersa,2026-03-30 01:02:37.813903,MXN
3,Fraccionamiento Las Parotas,250000.00,Hersa,2026-03-30 01:02:37.813903,MXN
4,Residencial Pirámide del Sol,500000.00,Hersa,2026-03-30 01:02:37.813903,MXN
5,Fraccionamiento La Aurora,180000.00,Hersa,2026-03-30 01:02:37.813903,MXN
6,Fraccionamiento Hacienda Camino Real,280000.00,Hersa,2026-03-30 01:02:37.813903,MXN
7,Colinas de Regadío,70000.00,Hersa,2026-03-30 01:02:37.813903,MXN
8,Fraccionamiento Altos San Miguel,160000.00,Hersa,2026-03-30 01:02:37.813903,MXN
9,Fraccionamiento Arcangel,200000.00,Hersa,2026-03-30 01:02:37.813903,MXN

#### Bayside

In [55]:
##

cookies = {
    '_omappvp': 'HowieCVlykfMOWxPuqFNXD0iGfHwrqw3GnDU4GYBf2rt0EPMYqMeAj50d0rsDv94kYbdMMHDZN6M7M1agGVkWXasEwkiJnc3',
    'AMP_MKTG_8f1ede8e9c': 'JTdCJTdE',
    '_ga': 'GA1.2.1858225868.1773099937',
    'AMP_8f1ede8e9c': 'JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJkM2M4NTA4NC0wOGU2LTQxMjUtODA1OC05ZTE2MzllNGFhZGQlMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzczMTk0NDU3NzI0JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlN0Q=',
    'PHPSESSID': '7p3b183pl4vf9bvsp9t6r5aar6',
    'iTracker360_2620': 'sou%3Ddirect%7Cmed%3Dnone%7Cter%3D-%7Ccon%3D-%7Ccam%3Ddirect%7Cref%3Dhttps%253A//baysiderealestate.com/advanced-search/%7Cfirstlpurl%3Dhttps%253A//baysiderealestate.com/advanced-search/%7Cgcl%3D%7Cmcl%3D%7Cfcl%3D%7Cgaclientid%3D%7Cfbp%3D%7Cfbc%3D%7Cleadsource%3Ddirect%7Cip%3D%7Ccustomfield1%3D-%7Ccustomfield2%3D-%7Ccustomfield3%3D-%7Ccustomfield4%3D-',
    '_gid': 'GA1.2.902275613.1774850255',
    'AMP_8f1ede8e9c': 'JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJkM2M4NTA4NC0wOGU2LTQxMjUtODA1OC05ZTE2MzllNGFhZGQlMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzczMTk0NDU3NzI0JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlN0Q=',
}

headers = {
    'accept': 'application/json, text/javascript, */*; q=0.01',
    'accept-language': 'es-US,es-419;q=0.9,es;q=0.8',
    'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'origin': 'https://baysiderealestate.com',
    'priority': 'u=1, i',
    'referer': 'https://baysiderealestate.com/advanced-search/',
    'sec-ch-ua': '"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36',
    'x-requested-with': 'XMLHttpRequest',
    # 'cookie': '_omappvp=HowieCVlykfMOWxPuqFNXD0iGfHwrqw3GnDU4GYBf2rt0EPMYqMeAj50d0rsDv94kYbdMMHDZN6M7M1agGVkWXasEwkiJnc3; AMP_MKTG_8f1ede8e9c=JTdCJTdE; _ga=GA1.2.1858225868.1773099937; AMP_8f1ede8e9c=JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJkM2M4NTA4NC0wOGU2LTQxMjUtODA1OC05ZTE2MzllNGFhZGQlMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzczMTk0NDU3NzI0JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlN0Q=; PHPSESSID=7p3b183pl4vf9bvsp9t6r5aar6; iTracker360_2620=sou%3Ddirect%7Cmed%3Dnone%7Cter%3D-%7Ccon%3D-%7Ccam%3Ddirect%7Cref%3Dhttps%253A//baysiderealestate.com/advanced-search/%7Cfirstlpurl%3Dhttps%253A//baysiderealestate.com/advanced-search/%7Cgcl%3D%7Cmcl%3D%7Cfcl%3D%7Cgaclientid%3D%7Cfbp%3D%7Cfbc%3D%7Cleadsource%3Ddirect%7Cip%3D%7Ccustomfield1%3D-%7Ccustomfield2%3D-%7Ccustomfield3%3D-%7Ccustomfield4%3D-; _gid=GA1.2.902275613.1774850255; AMP_8f1ede8e9c=JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJkM2M4NTA4NC0wOGU2LTQxMjUtODA1OC05ZTE2MzllNGFhZGQlMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzczMTk0NDU3NzI0JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlN0Q=',
}

data = {
    'action': 'wpestate_custom_ondemand_pin_load',
    'search_type': '3',
    'val_holder[]': [
        'all',
        'puerto-escondido',
        'all',
        'all',
        'all',
        '',
        'all',
        '0',
    ],
    'newpage': '0',
    'postid': '1',
    'halfmap': '1',
    'slider_min': '0',
    'slider_max': '7000000',
    'all_checkers': '',
    'filter_search_action10': '',
    'adv_location10': '',
    'filter_search_action11': '',
    'filter_search_categ11': '',
    'geo_lat': '',
    'geo_long': '',
    'geo_rad': '',
    'term_counter': 'NaN',
    'componentsbeds': '',
    'componentsbaths': '',
    'security': '162a19dc02',
}

response = requests.post('https://baysiderealestate.com/wp-admin/admin-ajax.php', cookies=cookies, headers=headers, data=data)
json_data = response.json()
json_data.keys()

dict_keys(['xxx', 'args', 'markers', 'no_results'])

In [56]:
propiedades_limpias = []

for m in json_data['markers']:
    # Extraer y limpiar la superficie (quitar comas y etiquetas HTML)
    superficie_raw = m[14]
    # Usamos regex para quedarnos solo con números y el punto decimal
    num_superficie = float(re.sub(r'[^\d.]', '', superficie_raw.split(' ')[0].replace(',', '')))
    
    # Conversión a metros cuadrados
    m2 = round(num_superficie * 0.092903, 2)
    
    # Armar el diccionario
    info = {
        "oferta": m[0].replace('%20', ' '), # Decodificar espacios URL
        "latitud": m[1],
        "longitud": m[2],
        "precio": m[11],
        "cuartos": m[12],
        "banos": m[13],
        "metros_cuad_const": m2
    }
    propiedades_limpias.append(info)

bayside = pd.DataFrame(propiedades_limpias)
#Añadir fuente y fecha de consulta
bayside["fuente"] = "Bayside Real Estate"
bayside["fecha_consulta"] = pd.Timestamp.now()
print("Total de registros extraídos:", len(bayside))
bayside

Total de registros extraídos: 50

,oferta,latitud,longitud,precio,cuartos,banos,metros_cuad_const,fuente,fecha_consulta
0,Eco Habitat 2 Bedroom Condo,15.857623,-97.070893,288000,2,2,148.92,Bayside Real Estate,2026-03-30 01:02:45.315294
1,Puerto Escondido Ocean View Hotel,15.862067,-97.069175,1543000,27,27,439.99,Bayside Real Estate,2026-03-30 01:02:45.315294
2,Panorama Coastal Residences In Puerto Escondido,15.831972,-97.038722,96000,1,1,26.11,Bayside Real Estate,2026-03-30 01:02:45.315294
3,3 Bedroom Oceanfront Modern Condo,15.857502,-97.068987,669000,3,2,199.56,Bayside Real Estate,2026-03-30 01:02:45.315294
4,1 Bedroom Poolside Condo,15.821020,-97.031940,125000,1,1,49.98,Bayside Real Estate,2026-03-30 01:02:45.315294
5,Oceanfront Carrizalillo 2 Bedroom Condo,15.859948,-97.083815,579000,2,2,161.93,Bayside Real Estate,2026-03-30 01:02:45.315294
6,Selva Blanca Coastal Condos,15.844394,-97.049905,136000,1,1,44.41,Bayside Real Estate,2026-03-30 01:02:45.315294
7,Puerto Escondido Coastal Home,15.845142,-97.040613,538000,2,4,221.95,Bayside Real Estate,2026-03-30 01:02:45.315294
8,Puerto Escondido 5 Bedroom Pool Home,15.869333,-97.072643,578000,5,5,311.97,Bayside Real Estate,2026-03-30 01:02:45.315294
9,Beautiful Ocean View Loft in Puerto Escondido,15.863302,-97.062955,214000,1,1,53.98,Bayside Real Estate,2026-03-30 01:02:45.315294
10,Prime Coastal Lot Steps to the Beach,15.760278,-96.880722,168000,0,0,500.00,Bayside Real Estate,2026-03-30 01:02:45.315294
11,Rinconada Villa with Rooftop Ocean Views,15.861778,-97.081056,1299000,8,9,511.99,Bayside Real Estate,2026-03-30 01:02:45.315294
12,Ocean View Puerto Escondido Studio,15.820274,-97.032664,139000,1,1,59.92,Bayside Real Estate,2026-03-30 01:02:45.315294
13,Oceanfront Puerto Escondido 2 Bedroom Condo,15.859532,-97.083722,569000,2,2,161.00,Bayside Real Estate,2026-03-30 01:02:45.315294
14,Rinconada Commercial Space,15.861700,-97.078658,283000,0,1,136.47,Bayside Real Estate,2026-03-30 01:02:45.315294
15,Contemporary 2 Bedroom Coastal Residence,15.845187,-97.049410,377000,2,2,100.43,Bayside Real Estate,2026-03-30 01:02:45.315294
16,Modern 1 Bedroom Coastal Condo,15.845187,-97.049410,219000,1,1,56.76,Bayside Real Estate,2026-03-30 01:02:45.315294
17,Luxury 4 Bedroom Beachfront Villa,15.817611,-97.033694,2999000,4,5,399.95,Bayside Real Estate,2026-03-30 01:02:45.315294
18,Puerto Escondido Beachside Home,15.817234,-97.032530,929999,3,3,230.03,Bayside Real Estate,2026-03-30 01:02:45.315294
19,Rare Beach Lot in La Punta Zicatela,15.834318,-97.043503,265000,0,0,285.03,Bayside Real Estate,2026-03-30 01:02:45.315294
20,Ocean View Puerto Escondido Duplex,15.848572,-97.043625,162000,1,1,51.65,Bayside Real Estate,2026-03-30 01:02:45.315294
21,Modern Beach Studio in Puerto Escondido,15.848572,-97.043625,118000,1,1,40.51,Bayside Real Estate,2026-03-30 01:02:45.315294
22,Puerto Escondido Beach Lofts,15.848572,-97.043625,133000,1,1,45.24,Bayside Real Estate,2026-03-30 01:02:45.315294
23,1 Bed La Punta Condo,15.834799,-97.042343,231000,1,2,59.74,Bayside Real Estate,2026-03-30 01:02:45.315294
24,2 Bed La Punta Condo,15.834799,-97.042343,263000,2,2,67.73,Bayside Real Estate,2026-03-30 01:02:45.315294
25,Beachfront Villa in Puerto Escondido,15.859312,-97.059452,649000,2,2,233.47,Bayside Real Estate,2026-03-30 01:02:45.315294
26,1 Bed Puerto Escondido Oasis,15.844546,-97.045739,370000,1,2,180.51,Bayside Real Estate,2026-03-30 01:02:45.315294
27,La Escondida Villa,15.857992,-97.066101,999000,4,4.5,382.95,Bayside Real Estate,2026-03-30 01:02:45.315294
28,Puerto Escondido Beachfront Houses,15.940311,-97.380431,405000,3,3.5,152.18,Bayside Real Estate,2026-03-30 01:02:45.315294
29,Casa Huizache %7C Beachfront Villa,15.920831,-97.201222,995000,4,4.5,356.00,Bayside Real Estate,2026-03-30 01:02:45.315294
30,Casa Mezquite %7C Beachfront Villa,15.920842,-97.201222,849000,4,4.5,356.00,Bayside Real Estate,2026-03-30 01:02:45.315294
31,Casa Pochote %7C Beachfront Villa,15.920831,-97.201222,995000,4,4.5,356.00,Bayside Real Estate,2026-03-30 01:02:45.315294
32,2 Bed Oceanfront Condo,15.840169,-97.047847,448000,2,2,114.92,Bayside Real Estate,2026-03-30 01:02:45.315294
33,3 Bedroom Carrizalillo Villa,15.860527,-97.081312,669000,3,2.5,264.03,Bayside Real Estate,2026-03-30 01:02:45.315294
34,Ocean View 3 Bedroom Villa,15.859312,-97.059452,299000,3,2,124.95,Bayside Real Estate,2026-03-30 01:02:45.315294
35,2 Bedroom Puerto Escondido Home,15.891511,-97.118430,375000,2,2.5,195.65,Bayside Real Estate,2026-03-30 01:02:45.315294
36,Fully Furnished Home with Exclusive Amenities,15.913580,-97.173583,419000,2,4,267.00,Bayside Real Estate,2026-03-30 01:02:45.315294
37,Osaka Condos La Punta,15.841759,-97.046724,167000,1,1,55.83,Bayside Real Estate,2026-03-30 01:02:45.315294
38,Grava Zicatela Condos,15.848009,-97.050496,261000,2,2,82.96,Bayside Real Estate,2026-03-30 01:02:45.315294
39,4 Bedroom Palmarito Home,15.913600,-97.176854,799000,4,5,609.63,Bayside Real Estate,2026-03-30 01:02:45.315294
40,Tabachin La Punta Condos,15.841017,-97.047740,195000,1,1,61.97,Bayside Real Estate,2026-03-30 01:02:45.315294
41,2 Bedroom La Punta Zicatela House,15.834355,-97.038818,549000,2,2,352.38,Bayside Real Estate,2026-03-30 01:02:45.315294
42,Rancho Neptuno Lot,15.793260,-96.955322,199000,0,0,1679.96,Bayside Real Estate,2026-03-30 01:02:45.315294
43,Puerto Escondido 2 Bedroom Single Family Home,15.892222,-97.118353,419000,2,4,226.96,Bayside Real Estate,2026-03-30 01:02:45.315294
44,Puerto Escondido Palmarito Lot,15.913098,-97.177146,231000,0,0,799.89,Bayside Real Estate,2026-03-30 01:02:45.315294
45,Direct Beach Access Puerto Escondido Condo,15.818520,-97.033116,590000,2,2.5,155.98,Bayside Real Estate,2026-03-30 01:02:45.315294
46,Eco Luxury Villa,15.819050,-97.037401,1600000,4,4.5,349.97,Bayside Real Estate,2026-03-30 01:02:45.315294
47,Cabeza de Tortuga Oceanfront Villa Puerto Esco...,15.763531,-96.894367,1650000,5,6,475.01,Bayside Real Estate,2026-03-30 01:02:45.315294
48,Casa Piedra Beachfront Retreat,15.740590,-96.852751,1600000,11,11.5,9499.52,Bayside Real Estate,2026-03-30 01:02:45.315294
49,1 Bedroom Beachfront Condo,15.840169,-97.047847,249000,1,1,74.79,Bayside Real Estate,2026-03-30 01:02:45.315294

#### Tabla final

In [57]:
df_final=pd.concat([mexhome_df, osanpuerto, realestatepuerto,century21,pxm,pincali_data,
                    gr8, matrona,puertoproperty,inmobisur,madre_ceiba,vivamexico,hersa,bayside], ignore_index=True)
print("Total de registros:", len(df_final))
#Guardar en excel
df_final.to_excel("puerto_escondido_real_estate.xlsx", index=False)

Total de registros: 771